edition: '1.0.0'

name: MagicQuill CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

services:
  your-service-name:
    component: fc
    props:
      region: cn-hangzhou
      account:
        accessKeyId: ${env:ALIYUN_ACCESS_KEY_ID}
        accessKeySecret: ${env:ALIYUN_ACCESS_KEY_SECRET}
      service:
        name: your-service-name
        description: Your service description
      function:
        name: your-function-name
        runtime: python3
        handler: index.handler
        codeUri: ./
        memorySize: 512
        timeout: 60
